# Generated by Django 3.1.1 on 2020-09-16 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='registro',
            table='Registro',
        ),
    ]
