# Generated by Django 3.1.1 on 2020-09-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200917_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='telefono',
            field=models.BigIntegerField(),
        ),
    ]
