# Generated by Django 3.1.1 on 2020-09-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_registro_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='user',
        ),
        migrations.AddField(
            model_name='registro',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date joined'),
        ),
        migrations.AddField(
            model_name='registro',
            name='last_login',
            field=models.DateTimeField(auto_now=True, verbose_name='last login'),
        ),
        migrations.AlterModelTable(
            name='registro',
            table=None,
        ),
    ]
